apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.images.logstash.name }}
  namespace: {{ .Values.namespace }}   
  labels:
    app: {{ .Values.images.logstash.name }}
    chart: {{ .Values.images.logstash.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.images.logstash.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}
      labels:
        app: {{ .Values.images.logstash.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.images.logstash.name }}
          image: "{{ .Values.images.logstash.repository }}:{{ .Values.deployment.elkversion }}"
          imagePullPolicy: {{ .Values.images.openscout.pullPolicy }}
          volumeMounts:
          - mountPath: {{ .Values.volumes.pipeline.mountPath }}
            name: pipeline
          ports:
            - containerPort: {{ .Values.logstashservice.port }}
              hostPort: {{ .Values.logstashservice.targetPort }}      
              protocol: {{ .Values.deployment.protocol }}
      volumes:
      - name: pipeline
        hostPath:
          path: {{ .Values.volumes.pipeline.hostPath }}

